### PR TITLE
Make <*> left associative

### PR DESCRIPTION
**Pull request by croyzor**

### CODE REVIEW

**Comment by laMudri** [comment]
This is the right thing, but I'm not sure which number should be here. Maybe 4 is right – it should at least be bigger than what `_,_` has, which is:

```agda
 infixr 2 _,_ -- should be low, but probably not that low
```

**Comment by croyzor** [comment]
I just copied from the haskell prelude without much thought!

The code that drove me down this avenue was akin to `pure _,-_ <*> f x <*> g y z` and I was satisfied that it now doesn't need any brackets

**Comment by laMudri** [comment]
I guess we'll see what Conor decides, now that he knows there's something to decide. 😛

**Comment by laMudri** [comment]
We could do with one of these on `_<*All*>_` in exercise 2, too.

**Pull request merged**
